### ISSUE TITLE
Escape the dot after 1660 so markdown doesn't turn it into a list

### ISSUE THREAD

**Issue by LeonSkills** [jclocks/levy-rozbot#10]
Github also uses markdown, so it'll look similar here:

1660. 1660. You're telling me a 1600 hung a piece on move 6?

Escape the dot after the first 1660 and it should be fine.

1660\. 1660. You're telling me a 1600 hung a piece on move 6?

How it looks on old.reddit: 
![image](https://user-images.githubusercontent.com/38615386/149035580-6ad778c6-c48c-47bd-872d-091eb37da0e9.png)

**Comment by jclocks** [comment]
See latest reply in https://www.reddit.com/r/AnarchyChess/comments/s0s9on/comment/hs9yt2p/?utm_source=share&utm_medium=web2x&context=3, should now be good. Tested in Old Reddit and "Reddit is Fun" (per #4.)
